//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pipeworks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pipeworks.localisations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить приложение в список.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть директорию приложения.
        /// </summary>
        public static string BrowseApp {
            get {
                return ResourceManager.GetString("BrowseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрать приложение из списка.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это уже есть в списке, пропускаю :).
        /// </summary>
        public static string DuplicateDesc {
            get {
                return ResourceManager.GetString("DuplicateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дубликат.
        /// </summary>
        public static string DuplicateTitle {
            get {
                return ResourceManager.GetString("DuplicateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить настройки приложения.
        /// </summary>
        public static string EditApp {
            get {
                return ResourceManager.GetString("EditApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить приложение.
        /// </summary>
        public static string PlayApp {
            get {
                return ResourceManager.GetString("PlayApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезагрузить список.
        /// </summary>
        public static string ReloadButton {
            get {
                return ResourceManager.GetString("ReloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить описание из Steam (Не всегда работает!).
        /// </summary>
        public static string Steam {
            get {
                return ResourceManager.GetString("Steam", resourceCulture);
            }
        }
    }
}
