name: Build pipeworks

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet packages
        run: dotnet restore pipeworks.sln

      - name: Build project
        run: dotnet build pipeworks.sln --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ./pipeworks/pipeworks.csproj --configuration Release --output ./publish

#      - name: Upload artifact
#        uses: actions/upload-artifact@v3.1.3 # я ненавижу гитхуй
#        with:
#          name: pipeworks-build
#          path: ./publish

      - name: List publish output
        run: dir ./publish

